// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WishlistBot.Model.User;

#nullable disable

namespace WishlistBot.Migrations.User
{
    [DbContext(typeof(UserContext))]
    [Migration("20251029214020_AdjustListPosition")]
    partial class AdjustListPosition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("WishlistBot.Model.User.BroadcastModel", b =>
                {
                    b.Property<int>("BroadcastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateTimeSent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BroadcastId");

                    b.ToTable("Broadcasts");
                });

            modelBuilder.Entity("WishlistBot.Model.User.LinkModel", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WishDraftId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WishId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LinkId");

                    b.HasIndex("WishDraftId");

                    b.HasIndex("WishId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("WishlistBot.Model.User.ListPositionModel", b =>
                {
                    b.Property<int>("ListPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.HasKey("ListPositionId");

                    b.ToTable("ListPositionModel");
                });

            modelBuilder.Entity("WishlistBot.Model.User.ListPositionsModel", b =>
                {
                    b.Property<int>("ListPositionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdminBroadcastPageListPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdminUserPageListPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClaimPageListPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriberPageListPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriptionPageListPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WishPageListPositionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ListPositionsId");

                    b.HasIndex("AdminBroadcastPageListPositionId");

                    b.HasIndex("AdminUserPageListPositionId");

                    b.HasIndex("ClaimPageListPositionId");

                    b.HasIndex("SubscriberPageListPositionId");

                    b.HasIndex("SubscriptionPageListPositionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WishPageListPositionId");

                    b.ToTable("ListPositionsModel");
                });

            modelBuilder.Entity("WishlistBot.Model.User.NotificationModel", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extra")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("NotificationId");

                    b.HasIndex("SourceId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WishlistBot.Model.User.ProfileModel", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProfileModel");
                });

            modelBuilder.Entity("WishlistBot.Model.User.ReceivedBroadcastModel", b =>
                {
                    b.Property<int>("ReceivedBroadcastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BroadcastId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReceivedBroadcastId");

                    b.HasIndex("BroadcastId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("ReceivedBroadcasts");
                });

            modelBuilder.Entity("WishlistBot.Model.User.SettingsModel", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SettingsId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("WishlistBot.Model.User.SubscriptionModel", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("TargetId");

                    b.HasIndex("SubscriberId", "TargetId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("WishlistBot.Model.User.UserExtraModel", b =>
                {
                    b.Property<int>("UserExtraModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastCleanedMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserExtraModelId");

                    b.HasIndex("UserId");

                    b.ToTable("UserExtra");
                });

            modelBuilder.Entity("WishlistBot.Model.User.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedQueries")
                        .HasColumnType("TEXT");

                    b.Property<int>("BotState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastBotMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastQueryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryParams")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscribeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WishlistBot.Model.User.WishDraftModel", b =>
                {
                    b.Property<int>("WishDraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClaimerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceRange")
                        .HasColumnType("INTEGER");

                    b.HasKey("WishDraftId");

                    b.HasIndex("ClaimerId");

                    b.HasIndex("OriginalId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("WishDrafts");
                });

            modelBuilder.Entity("WishlistBot.Model.User.WishModel", b =>
                {
                    b.Property<int>("WishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClaimerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceRange")
                        .HasColumnType("INTEGER");

                    b.HasKey("WishId");

                    b.HasIndex("ClaimerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Wishes");
                });

            modelBuilder.Entity("WishlistBot.Model.User.WishViewSettingsModel", b =>
                {
                    b.Property<int>("WishViewSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Descending")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnlyUnclaimed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortProperty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WishViewSettingsId");

                    b.HasIndex("TargetId");

                    b.HasIndex("ViewerId");

                    b.ToTable("WishViewSettingsModel");
                });

            modelBuilder.Entity("WishlistBot.Model.User.LinkModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.WishDraftModel", "WishDraft")
                        .WithMany("Links")
                        .HasForeignKey("WishDraftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WishlistBot.Model.User.WishModel", "Wish")
                        .WithMany("Links")
                        .HasForeignKey("WishId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Wish");

                    b.Navigation("WishDraft");
                });

            modelBuilder.Entity("WishlistBot.Model.User.ListPositionsModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.ListPositionModel", "AdminBroadcastPage")
                        .WithMany()
                        .HasForeignKey("AdminBroadcastPageListPositionId");

                    b.HasOne("WishlistBot.Model.User.ListPositionModel", "AdminUserPage")
                        .WithMany()
                        .HasForeignKey("AdminUserPageListPositionId");

                    b.HasOne("WishlistBot.Model.User.ListPositionModel", "ClaimPage")
                        .WithMany()
                        .HasForeignKey("ClaimPageListPositionId");

                    b.HasOne("WishlistBot.Model.User.ListPositionModel", "SubscriberPage")
                        .WithMany()
                        .HasForeignKey("SubscriberPageListPositionId");

                    b.HasOne("WishlistBot.Model.User.ListPositionModel", "SubscriptionPage")
                        .WithMany()
                        .HasForeignKey("SubscriptionPageListPositionId");

                    b.HasOne("WishlistBot.Model.User.UserModel", "User")
                        .WithOne("ListPositions")
                        .HasForeignKey("WishlistBot.Model.User.ListPositionsModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WishlistBot.Model.User.ListPositionModel", "WishPage")
                        .WithMany()
                        .HasForeignKey("WishPageListPositionId");

                    b.Navigation("AdminBroadcastPage");

                    b.Navigation("AdminUserPage");

                    b.Navigation("ClaimPage");

                    b.Navigation("SubscriberPage");

                    b.Navigation("SubscriptionPage");

                    b.Navigation("User");

                    b.Navigation("WishPage");
                });

            modelBuilder.Entity("WishlistBot.Model.User.NotificationModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.UserModel", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("WishlistBot.Model.User.ProfileModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.UserModel", "User")
                        .WithOne("Profile")
                        .HasForeignKey("WishlistBot.Model.User.ProfileModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WishlistBot.Model.User.ReceivedBroadcastModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.BroadcastModel", "Broadcast")
                        .WithMany()
                        .HasForeignKey("BroadcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WishlistBot.Model.User.UserModel", "Receiver")
                        .WithMany("ReceivedBroadcasts")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broadcast");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("WishlistBot.Model.User.SettingsModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.UserModel", "User")
                        .WithOne("Settings")
                        .HasForeignKey("WishlistBot.Model.User.SettingsModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WishlistBot.Model.User.SubscriptionModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.UserModel", "Subscriber")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WishlistBot.Model.User.UserModel", "Target")
                        .WithMany("Subscribers")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("WishlistBot.Model.User.UserExtraModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WishlistBot.Model.User.WishDraftModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.UserModel", "Claimer")
                        .WithMany()
                        .HasForeignKey("ClaimerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WishlistBot.Model.User.WishModel", "Original")
                        .WithMany()
                        .HasForeignKey("OriginalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WishlistBot.Model.User.UserModel", "Owner")
                        .WithOne("CurrentWish")
                        .HasForeignKey("WishlistBot.Model.User.WishDraftModel", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claimer");

                    b.Navigation("Original");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WishlistBot.Model.User.WishModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.UserModel", "Claimer")
                        .WithMany("ClaimedWishes")
                        .HasForeignKey("ClaimerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WishlistBot.Model.User.UserModel", "Owner")
                        .WithMany("Wishes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claimer");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WishlistBot.Model.User.WishViewSettingsModel", b =>
                {
                    b.HasOne("WishlistBot.Model.User.UserModel", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WishlistBot.Model.User.UserModel", "Viewer")
                        .WithMany("WishViewSettings")
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("WishlistBot.Model.User.UserModel", b =>
                {
                    b.Navigation("ClaimedWishes");

                    b.Navigation("CurrentWish");

                    b.Navigation("ListPositions")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("ReceivedBroadcasts");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Subscribers");

                    b.Navigation("Subscriptions");

                    b.Navigation("WishViewSettings");

                    b.Navigation("Wishes");
                });

            modelBuilder.Entity("WishlistBot.Model.User.WishDraftModel", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("WishlistBot.Model.User.WishModel", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
