// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WishlistBot.Model;

#nullable disable

namespace WishlistBot.Migrations.MediaStorage
{
    [DbContext(typeof(MediaStorageContext))]
    partial class MediaStorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("WishlistBot.Model.MediaItemModel", b =>
                {
                    b.Property<int>("MediaItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId");

                    b.ToTable("StoredMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
